INSERT INTO tokens (token_id,name) VALUES(0,'wrench');
INSERT INTO tokens (token_id,name) VALUES(1,'sword');
INSERT INTO tokens (token_id,name) VALUES(2,'airplane');
INSERT INTO tokens (token_id,name) VALUES(3,'suitcase');
INSERT INTO tokens (token_id,name) VALUES(4,'star');
INSERT INTO tokens (token_id,name) VALUES(5,'rocket');
INSERT INTO tokens (token_id,name) VALUES(6,'pin');
INSERT INTO tokens (token_id,name) VALUES(7,'scissors');
